### ISSUE TITLE
Analysis Examples, Smoothing & Date Range

### ISSUE THREAD

**Issue by jonathanrjpereira** [jonathanrjpereira/Ngram-Analytica#1]
We need help with a few basic projects that are ideal for first-time contributors. Check them out at [Projects](https://github.com/jonathanrjpereira/Ngram-Analytica/projects)

Some of them include:
- Basic examples for manipulating & graphing the data. (Min/Max, Average, Slope, etc).
- Select the Start Year & End Year of the graph.
- Selecting the smoothing of the graph from 0 - 50.

**Comment by jonathanrjpereira** [comment]
- Select the Start Year & End Year of the graph.
- Selecting the smoothing of the graph from 0 - 50.
These projects are now complete thanks to @ArionMiles.

**Comment by ArionMiles** [comment]
Can you elaborate on the Analysis Examples? what are we supposed to do?

**Comment by jonathanrjpereira** [comment]
Basic examples of what we can find out from the graph data. 
For example, one may want to find out the maximum/minimum frequency across the entire graph. Or the average frequency of a few years. Or even the slope of the graph for a given time period.

Example:
 Slope of the graph between year 1800 to 1900.
Average frequency between 1850 to 1950
